blog/article/urls.py
from django.conf.urls import url 
from article import views
urlpatterns = [
url(r'^$', views.article, name='article'), 
]

blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/',include("main.urls", namespace='main')),
    url(r'^article/',include("article.urls", namespace='article')),
    url(r'^contact/',include("contact.urls", namespace='contact')),
    url(r'^.*', include('main.urls')),
    
]

blog/contact/urls.py
from django.conf.urls import url 
from contact import views
urlpatterns = [
    url(r'^$', views.contact, name='contact'), 
]

blog/main/urls.py
from django.conf.urls import url 
from main import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
]

blog/article/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True) 
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def __str__(self): 
        return self.title
    
    class Meta:
        ordering = ('-pubDateTime', )

class Comment(models.Model):
    article = models.ForeignKey(Article) 
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)

blog/contact/models.py
from django.db import models

# Create your models here.

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/views.py
from django.shortcuts import render
from article.models import Article, Comment


def article(request):
    '''
    Render the article page
    '''
    
    articles = Article.objects.all()
    itemsList = []
    for article in articles:
        items = [article] 
        items.extend(list(Comment.objects.filter(article=article))) 
        itemsList.append(items)
    context = {'itemsList':itemsList}
    
    return render(request, 'article/article.html',context)
# Create your views here.

blog/contact/views.py
from django.shortcuts import render
import datetime

def contact(request):
    '''
    Render the contact page
    '''
    context={ 'now':datetime.datetime.now()}
    return render(request,'contact/contact.html',context)

blog/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    '''
    Render the main page
    '''
    now = datetime.datetime.now()
    context = {'like':'Django 很棒','now':now}
    
    if now.hour >= 6 and now.hour < 12 :
        context.update({'greeting': "morning"})
    elif now.hour >= 12:
        context.update({'greeting': "afternoon"})
    return render(request,'main/main.html',context)

def about(request):
    '''
    Render the about page
    '''
    return render(request,'main/about.html')
# Create your views here.

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %} <html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}"> 
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格說--Hello world!!!!!</h2>
<h2>歡迎來到我的部落格</h2> <br>
{% for items in itemsList %}
{% for item in items %} 
{% if forloop.first %}
<h3>{{ item.title }}</h3>
<p>發表時間:{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
<div class=articleContent>{{ item.content|linebreaks|truncatechars_html:30 }}</div> 
<p>讚:{{ item.likes }}</p>
{% else %} <p>
<span class=comment>{{ item.content }}</span><br>
<span class=commentTime>{{ item.pubDateTime|date:'m 月 d 日 H:i'}}</span> 
</p>
{% endif %}
{% endfor %}
<hr>
{% endfor %}

 </body>
</html>

blog/contact/templates/contact/contact.html
<!doctype html>
<html>
<head>
<title>Contact Us</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'contact/css/contact.css'}"
</head>
<body>
   <h1>HELLO!!!!</h1>
   <p>Current: {{ now }} <p>

</body>
</html>

blog/main/templates/main/about.html
<!doctype html> 
{% load staticfiles %}
<html>
<head>
<title>部落格</title> <meta charset="utf-8"></head>
<body>
{% include 'main/menu.html' %}
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<ul>
<li><a href="{% url 'main:about' %}">首頁2</a></li>
<li><a href="{% url 'main:about' %}">關於2</a></li> </ul>
<h2>關於部落格</h2>
<p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p> </body>
</html>

blog/main/templates/main/main.html
<!doctype html> 
{% load staticfiles %}
<html>
<head>
<title>部落格</title> 
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>Django 說--Hello world!</h2> <p>{{ like }}</p>
<p>Current Time: {{ now }}</p>



<p>greeting!:{{ greeting }}</p>

<img src="{% static 'main/img/聯絡我們.png' %}">


<a href="/main/about/">ABOUT</a>
</body>
</html>

blog/main/templates/main/menu.html
<!doctype html>
<<html>
<ul>
<li><a href="{% url 'main:main' %}">首頁3</a></li>
<li><a href="{% url 'main:about' %}">關於3</a></li> </ul>
<li><a href="{% url 'article:article' %}">部落格</a></li>
</html>